# Attempts to update dates on index.html from google ical
name: Update index dates

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */4 * * *"

jobs:
  mangle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up git
        run: |
          git config user.email "bot@dorkbotpdx.org"
          git config user.name "DorkbotPDX Bot"
      - name: try and update index
        run: |
          branch="automated/update-event-dates-$(date +%Y%m%d%H%M%S)"
          git checkout -b $branch
          .github/scripts/update_dates.sh
          if git diff-index --quiet HEAD --; then
            echo "No chnages to the calendar right now."
          else
            git commit -am "New event dates added"
            git push --set-upstream origin $branch
            echo "HAVE_CHANGES=1" >> $GITHUB_OUTPUT
          fi
  pr_if_changes:
    runs-on: ubuntu-latest
    needs: mangle
    if: ${{needs.mangle.outputs.output1}} == 1
    steps:
      - name: create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --title "[automated] Calendar events updated" \
                       --body "Upcoming meeting dates have been updated!" \
                       --base main
