# Attempts to update dates on index.html from google ical
name: Update index dates

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */4 * * *"

jobs:
  mangle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: try and update index
        run: |
          branch="automated/update-event-dates-$(date +%Y%m%d%H)"
          git checkout -b $branch
          .github/scripts/update_dates.sh
      - name: create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --title "[automated] Calendar events updated" \
                       --body "Upcoming meeting dates have been updated!" \
                       --base main
